name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # ✅ Install Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # ✅ Accept licenses
      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      # ✅ Build with Gradle Wrapper (IMPORTANT)
      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: fintech-apk
          path: app/build/outputs/apk/debug/app-debug.apk
